from django.urls import path
from . import views

urlpatterns = [
    path("", views.home),
    path("topics/", views.topics),
    path("projects/", views.projects),
    path("packages/", views.packages),
    path("facts/", views.facts),
    path("a/", views.a),
    path("b/", views.b),
    path("c/", views.c),
    path("d/", views.d),
    path("e/", views.e),
    path("f/", views.f),
    path("g/", views.g),
    path("h/", views.h),
    path("i/", views.i),
    path("j/", views.j),
    path("k/", views.k),
    path("l/", views.l),
    path("m/", views.m),
    path("n/", views.n),
    path("o/", views.o),
    path("p/", views.p),
    path("q/", views.q),
    path("r/", views.r),
    path("s/", views.s),
    path("t/", views.t),
    path("u/", views.u),
    path("v/", views.v),
    path("w/", views.w),
    path("x/", views.x),
    path("y/", views.y),
    path("z/", views.z),
    path("hex/", views.hex),
    path("BB/", views.BB),
    path("CC/", views.CC),
    path("DD/", views.DD),
    path("EE/", views.EE),
    path("FF/", views.FF),
    path("GG/", views.GG),
    path("HH/", views.H),
    path("II/", views.I),
    path("JJ/", views.J),
    path("KK/", views.K),
    path("LL/", views.L),
    path("MM/", views.M),
    path("NN/", views.N),
    path("OO/", views.O),
    path("PP/", views.P),
    path("QQ/", views.Q),
    path("RR/", views.R),
    path("SS/", views.S),
    path("TT/", views.T),
    path("UU/", views.U),
    path("VV/", views.V),
    path("WW/", views.W),
    path("XX/", views.X),
    path("YY/", views.Y),
    path("ZZ/", views.Z),
    path("sidebar/", views.sidebar),
]

